# database configurations

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5434}/${DB_NAME:docmind}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true 

  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}

        chat:
          model: ${GEMINI_CHAT_MODEL:gemini-3.6-flash}
          temperature: 0.2

        embedding:
          api-key: ${GEMINI_API_KEY}
          text:
            model: gemini-embedding-001
            dimensions: 1536

    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
        table-name: vector_store
        schema-name: public
        initialize-schema: true

  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 50MB


# app configuration
app:
  frontend-url: ${FRONTEND_URL:http://localhost:5173}
  email:
    resend-api-key: ${RESEND_API_KEY}
    from: onboarding@resend.dev
  rag:
    chunk-size: 700
    #chunk-overlap: 100
    top-k: 5
    similarity_threshold: 0.0

  cors:
    allowed-origins: "*"
    allowed-methods: GET,POST,PUT,PATCH,DELETE,OPTION
    allowed-headers: "*"


  #JWT Authentication

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000


bootui:
  enabled: ON


logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG